version: '2'
services:
  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis:6.2.4
    
  identidock:
    build: .
    expose:
      - "9090"
    environment:
      ENV: PROD
    links:
      - dnmonster
      - redis